export { default as DaftarAnak } from './daftaranak/DaftarAnak';
export { default as Footer } from './footer/Footer';
export { default as HasilPemeriksaan } from './hasilpemeriksaan/HasilPemeriksaan';
export { default as HeaderTitle } from './headertitle/HeaderTitle';
export { default as Klasifikasi } from './klasifikasi';
export { default as NavBar } from './navbar/NavBar';
export { default as RiwayatPemeriksaan } from './riwayatpemeriksaan/RiwayatPemeriksaan';
export { default as SideBar } from './sidebar/SideBar';
export { default as Summary } from './summary/Summary';
